# Base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/sigr_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=sigr_alomrane_secret_key_very_long_minimum_256_bits_secure
jwt.expiration=86400000


# CORS
frontend.url=http://localhost:3000

spring.application.name=sigr
server.port=8081

# LDAP embarqué (local)
spring.ldap.embedded.base-dn=dc=alomrane,dc=ma
spring.ldap.embedded.ldif=classpath:users.ldif
spring.ldap.embedded.port=8489

logging.level.org.springframework.security=DEBUG

# Désactiver l'auto-configuration de sécurité LDAP
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

